substitutions:
  _REGION: asia-southeast1
  _REPOSITORY: small-sme-erp-backend
  _SERVICE: small-sme-erp-backend
  _REPO_URL: https://github.com/kard80/small-sme-erp-backend.git
  _MONGODB_URI: ''
  _NODE_ENV: ''

steps:
  - id: clone
    name: gcr.io/cloud-builders/git
    args:
      - clone
      - --branch=$BRANCH_NAME
      - --depth=1
      - $_REPO_URL
      - .

  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$COMMIT_SHA
      - --tag
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest
      - --cache-from
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest
      - .

  - id: push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE

  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$COMMIT_SHA
      - --region=$_REGION
      - --platform=managed
      - --set-env-vars=MONGODB_URI=$_MONGODB_URI,NODE_ENV=$_NODE_ENV,GCS_KEY_FILENAME=/secrets/gcs-key.json
      - --set-secrets=/secrets/gcs-key.json=GCS_SERVICE_ACCOUNT_KEY:latest

images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:$COMMIT_SHA
  - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/$_SERVICE:latest

options:
  logging: CLOUD_LOGGING_ONLY
