name: Deploy to GCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create GCS key file
      run: echo '${{ secrets.GCS_SERVICE_ACCOUNT }}' > ./gcs-key.json

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/433818871135/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-deployer@ekkalak.iam.gserviceaccount.com'

    - name: Submit Cloud Build
      run: |
        gcloud builds submit --no-source --config=cloudbuild.yaml \
          --substitutions=BRANCH_NAME=${GITHUB_REF_NAME},COMMIT_SHA=${GITHUB_SHA},_MONGODB_URI=${{ secrets.MONGODB_URI }},_NODE_ENV=${{ secrets.NODE_ENV }},_GCS_KEY_FILENAME=${{ secrets.GCS_KEY_FILENAME }}